#version 460
#extension GL_NV_ray_tracing : require
// Need later, this is equiv of DXR non uniform resource index
//#extension GL_EXT_nonuniform_qualifier : enable

layout(binding = 0, set = 0) uniform accelerationStructureNV scene;
layout(binding = 1, set = 0, rgba8) uniform image2D framebuffer;

layout(location = 0) rayPayloadNV vec4 hitColor;

void main() {
	const ivec2 pixel = ivec2(gl_LaunchIDNV.xy);
	imageStore(framebuffer, pixel, vec4(1, 0, 0, 0));
}

